import { Nav } from "@/components/shared/nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConditionRecordsServiceProvider } from "@/services/condition-records.service.context";
import { Snackbar } from "@/components/shared/snackbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConditionRecordsServiceProvider>
          <>
            {children}
            <Nav />
            <Snackbar />
          </>
        </ConditionRecordsServiceProvider>
      </body>
    </html>
  );
}
